### PR TITLE
Avoid `clippy::equatable_if_let`

### PR DESCRIPTION
**Pull request by daxpedda**
I'm not sure why there was a `let` to begin with, I hope this wasn't a workaround for something.
This "fix" would avoid triggering a false-positive of `clippy::equatable_if_let`.

See https://github.com/rust-lang/rust-clippy/issues/9066.

### CODE REVIEW

**Comment by rodrimati1992** [comment]
Clippy is wrong, `if false =` prevents users from passing non-bools by overloading traits.

I'm avoiding this:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=76c0373a854a9a683f8c48becae77bc0

```rust
use std::cmp::PartialEq;

struct Falsy;

impl std::ops::Not for Falsy {
    type Output = bool;
    fn not(self) -> bool {
        true
    }
}

fn main(){
    assert!(Falsy);
}



// another way that bool can be compared with arbitrary types
impl PartialEq<Falsy> for bool {
    fn eq(&self, _: &Falsy) -> bool {
        *self == false
    }
}

// another way that bool can be compared with arbitrary types
impl PartialEq<bool> for Falsy {
    fn eq(&self, b: &bool) -> bool {
        *b == false
    }
}
```

```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 1.07s
     Running `target/debug/playground`
thread 'main' panicked at 'assertion failed: Falsy', src/main.rs:11:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by daxpedda** [comment]
@rodrimati1992 aha! Thanks for the explanation!

Would it be acceptable to do a `allow(clippy::equatable_if_let)` to mitigate the false-positive?

**Comment by rodrimati1992** [comment]
> @rodrimati1992 aha! Thanks for the explanation!
> 
> Would it be acceptable to do a `allow(clippy::equatable_if_let)` to mitigate the false-positive?

Yes, do it.

**Comment by daxpedda** [comment]
Done, had to add some extra bracers to work around "attributes on expressions are experimental".

**Pull request merged**
